spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ci9fygble29v.ap-northeast-2.rds.amazonaws.com:3306/sogonsogon?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root1
    password: sparta1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

cloud:
  aws:
    credentials:
      accessKey: AKIARRUBPVXH7PCWUG4G
      secretKey: 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
    s3:
      bucket: my-aws-bucket-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size:

cache:
  type: redis
  redis:
    time-to-live: 60000
    cache-null-values: true
redis:
  host: 127.0.0.1
  port: 6379

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 965278642925-77ja14nudttvnaf64agdd32kv96lkd3u.apps.googleusercontent.com
          client-secret: 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
          scope: profile, email
        naver:
          client-id: ICE5CFb855lqBdcrGW_h
          client-secret: llWjg3Q_D5
          redirect-uri: http://localhost:3000/login/oauth2/code/naver
          authorization-grant-type: authorization_code
          scope: name, email, nickname, profile-image
          client-name: Naver
        kakao:
          client-id: 1fe5286c93bd9272bbbec77f4c28cabc
          client-secret: 9DiaDEFkp5MKPSMHLBmZpDaUF8hm4hOt
          redirect-uri: http://localhost:3000/login/oauth2/code/kakao
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          client-name: Kakao
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me